### PR TITLE
Fix working with repo

### PR DESCRIPTION
**Pull request by goruha**

### CODE REVIEW

**Review by alexei-led — COMMENTED** [review]
@goruha Please squash commits into a single commit and remove `codefresh.yaml` from the commit (or at least use `codefresh` docker repo)

**Review by alexei-led — CHANGES_REQUESTED** [review]
Please, remove `codefresh.yaml` form PR. 
Thank you

**Review by alexei-led — CHANGES_REQUESTED** [review]
please update images in codefresh.yaml to codefresh Dockerhub repo

**Comment by goruha** [comment]
Created new PR https://github.com/codefresh-io/cf-plugin-helm/pull/11

**Pull request closed without merging**
